### ISSUE TITLE
HSR Scanner start to open "Bookshelf" instead of "Character" screen

### ISSUE THREAD

**Issue by supernova-ws** [kel-z/HSR-Scanner#13]
After recent HSR update (? not sure) HSR Scanner start behave weird - it opens "Bookshelf" screen instead of "Character"

Cones and relics opened and scanned normally

Same behavior on 0.2.2 and 0.2.1

2023-08-26 about 22:00 it works fine - got complete scan. Today - 2023-08-28 08:00 - it behaves erratically.

**Comment by supernova-ws** [comment]
![image](https://github.com/kel-z/HSR-Scanner/assets/412702/96ad20b0-ae50-48ed-9db5-2098bbd7e6bf)

Screen of main menu - HSR Scanner directly position mouse on "Bookshelf" button. Resolution is 1920x1080 - same as always. Also I changed nothing in keys/video settings. Audio is disabled

**Comment by supernova-ws** [comment]
![image](https://github.com/kel-z/HSR-Scanner/assets/412702/16834ec6-2f7e-4d8f-9946-5614d57ce68e)

If I scroll menu down a bit (just for test) - HSR Scanner now opens "Missions" menu.

Looks like

**Comment by supernova-ws** [comment]
Ah... May be it relates - battlepass ended yesterday.

**Comment by kel-z** [comment]
Oh, that's awkward (if it is because the battle pass ended). I might include a check for that in future versions.

**Comment by supernova-ws** [comment]
May be use "Esc" - "C" sequence to bring character screen? In Inventory Kamera (similar tool for Genshin Impact) they use binded keys to bring screens up and also there is setting to change binded keys.
IMHO "Esc" - "C" is more relevant method to bring char screen - because when I tried to found why HSR Scanner behave strangely I googled main menu button locations - and saw that in several ocassions (especially on early levels) "Character" button in cellphone menu can have several different position - depending on player's progress in game.

**Comment by kel-z** [comment]
I'm actually opening "Data Bank" from the ESC menu (not the character screen) to get the total character count so that the character scanner can align the mouse properly when scanning the final nine characters. The main reason why I didn't opt for using "ESC" - "C" is because people sometimes change the key that opens the character menu. Currently, the character menu is opened via the shortcut menu (TAB) which cannot be altered by the user.

There are a number of assumptions that I made when coding the character scanner. I figured that most people who are interested in snapshotting their Star Rail inventory are well beyond the early stages of the game, so that the "Data Bank" button would be in the correct position when they use the scanner. I also haven't checked how the scanner behaves for when a user has less than nine characters, but both of these are low priority for me since that would mean creating and playing on a new account (which I don't have time for 😢).

Evidently, my assumption for the "Data Bank" button always staying in one place was wrong (and sadly, there's no shortcut key for "Data Bank"), but it looks like it only gets moved one spot to the left when the battle pass ends. I will include a check for when this happens in the next version. Thanks again :)

**Comment by supernova-ws** [comment]
Ugh... Okay. Seems like I just should wait for new BP season.

Anyway - thanks for a great program! I'm very used to InventoryKamera/AkashaScanner in Genshin so it would be very hard to me to play in HSR without your program - especially when organizing/choosing relics.

**Comment by kel-z** [comment]
Haha my pleasure! Yeah I was obsessed with snapshotting my account progress in Genshin, so I wanted to do the same with Star Rail as soon as possible - which meant making my own program.

I took the time yesterday to create a proper solution for this bug in the future (such as when the battlepass ends again or the UI gets moved a bit). In the next version, the scanner will locate the Data Bank icon on the screen and then move the mouse to it, rather than relying on a hardcoded coordinate (so this will work for the different positions that the ESC menu can have early in the game). 

Next version will be out as soon as I confirm that the scanner works with the new banner characters.

**Comment by supernova-ws** [comment]
COOL! Thanks! Really - you program is life-saver! Even if I can re-type characters into Google Sheets - I will die typing all relics (or even important ones)!
