### ISSUE TITLE
HSR v1.3 makes character scan fully irrelevant

### ISSUE THREAD

**Issue by supernova-ws** [kel-z/HSR-Scanner#14]
Relates to all versions from 0.2.0 to 0.2.2

Scan results for different HSR-Scanner versions for chars
[HSR_chars.zip](https://github.com/kel-z/HSR-Scanner/files/12475245/HSR_chars.zip)
Scans was obtained by staring at black wall, in one run, not moving, not changing anything in same ESC menu instance

Results differs from scan to scan

All versions scans only 1st "page" of characters, never advanced to 2nd one.

![image](https://github.com/kel-z/HSR-Scanner/assets/412702/1078b753-f174-4bca-b08e-a0af9bc4f805)
Only this characters even attempts to be scanned.

Scan result irrelevant - multiple errors makes this unusable. Even basic character detection now not working

**Comment by supernova-ws** [comment]
My characters
![image](https://github.com/kel-z/HSR-Scanner/assets/412702/3521aa9c-cd77-4257-bd4d-76e7ea781ad2)
![image](https://github.com/kel-z/HSR-Scanner/assets/412702/a71e5539-bdbb-4ddc-a719-27f45a5400b4)

**Comment by kel-z** [comment]
Yeah, they changed the character screen behaviour this version so that opening the character list wouldn't reset the character bar position anymore when you closed the list, which is annoying. I've changed it to use drag-to-scroll method instead now, which can be inconsistent if something like the computer lags, but it should work for now.
