### ISSUE TITLE
Bug: HSR Scan fails if switch app on OCR stage

### ISSUE THREAD

**Issue by supernova-ws** [kel-z/HSR-Scanner#19]
If after scan phase when HSR Scanner OCRs screenshot I switch to other app - not HSR itself or HSR Scanner - sometime later will abort OCR and fail whole scan process. Especially it's annoying when scan fails after scanning 800+ relics.
For now I can't find exact sequence how to reproduce this behavior. I will monitor HSR Scanner behavior.

v.0.2.3 beta

**Comment by kel-z** [comment]
I think I know what you're talking about. The "press enter to cancel" still applies even after all the screenshotting is done, which I don't want. 

I'll change this so it doesn't remain in effect when the screenshotting process is done, since I've also had times when I would switch to Discord after scanning, only the find out that I cancelled the OCR because I pressed enter to send a message.

Thanks!

**Comment by supernova-ws** [comment]
Yes! That's looks like it. Now I recall that I may press "Enter" in cases when it's stopped OCRing. Unlocking "Enter" on OCR phase surely would be very cool!

**Comment by kel-z** [comment]
#21
