### ISSUE TITLE
[crash] 0.5.1b Hard error in OCR phase

### ISSUE THREAD

**Issue by supernova-ws** [kel-z/HSR-Scanner#45]
All HSRS version until now works w/o any errors. In 0.5.1b after several usages new error arises:

![image](https://github.com/kel-z/HSR-Scanner/assets/412702/3732fa86-df35-4cd1-b47c-b6fc52bd809b)

[19:25:26] > Starting scan...
[19:25:46] > Finished scanning light cones
[19:26:08] > Finished scanning relics
[19:26:50] > Finished scanning characters
[19:26:50] > Starting OCR process. Please wait...
[19:27:16] > Scan aborted with error: (3221225794, '')

I restarted HSRS - same happens again but even worse: whole PC becomes unresponsible and even Explorer dies and Chrome stops Youtube clip on background!

Later I will  try to restart PC and report.

**Comment by supernova-ws** [comment]
More info - all processes that still runs report "No memory"... Erhm... I have 24Gb memory uncommitted (aka free) when I start HSRS.

**Comment by kel-z** [comment]
Interesting, this looks like one of those errors that should go away when you restart your PC. I wonder if the executable got corrupted. Can you try redownloading the latest release?

**Comment by supernova-ws** [comment]
Redownloaded EXE file and compared it with current one - no binary diff.

**Comment by supernova-ws** [comment]
Reboot helped but I still a bit worried.

**Comment by kel-z** [comment]
Yeah, so rebooting your system clears your memory (including any "stuck" programs and data that were consuming memory, potentially due to memory leaks or inefficient memory usage, and gives you a clean slate). Tesseract (the "app" that fails to start in your error) is the tool used for OCR.

You could try monitoring the Task Manager to see if it is because of memory. (Open Task Manager and monitor the Performance tab to see how much memory is being used when running Tesseract to see if it is because of that, or if it's because of some other external thing on your system.)
